name: Publish

on:
  push:
    branches: # Snapshots
      - 5.0.x
    tags: ["*"] # Releases

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: playframework/.github/.github/workflows/publish.yml@v2
    secrets: inherit
